### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by joannakrasucka** [powerpuffIntership/powerpuff-internship#2]
The goal of this task is to add a favicon to the website.
Design: https://www.figma.com/design/D09gXGjycBxsrXo1GwxsPO/Letnie-praktyki?node-id=186-275&m=dev

**Comment by rsgodzajVatek** [comment]
Test scenrio : 
1. Check if the favicon is displaying correctly.
2. Check if favicon is the correct icon ( no angular icon visibile ) , icon is presented in the linked designs
3. Check if favicon is in the correct size.

**Comment by joannakrasucka** [comment]
For developer: 

Existing favicon should be replaced with new one designed for our solution
